version: '3.8'

services:
  app:
    build: .
    container_name: money-tracker-api
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moneytracker

  postgres:
    image: postgres:16
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moneytracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: